server:
  port: 433

lavalink:
  server:
    password: "wificuatoi"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    resamplingQuality: HIGH
    
